### ISSUE TITLE
Sample cron job needs updating

### ISSUE THREAD

**Issue by shibaobun** [reluce/szurubooru-toolkit#25]
Unfortunately, it seems like the example command in `crontab_sample` for the docker image cannot run, and needs to be modified to the following:
```
*/30 * * * *    cd /szurubooru-toolkit && /usr/local/bin/auto-tagger --add-tags deepbooru "-deepbooru -deepbooru" >/proc/1/fd/1 2>&1
```

Also, it seems like if you only want to search for a inverted tag (like `-deepbooru`), you have to append it twice, otherwise it errors with `auto-tagger: error: the following arguments are required: query`.

Thank you for all your work on this project!

**Comment by reluce** [comment]
The problem is that if your query starts with a dash (`-`), argparse will interpret it as an argument. There are some workarounds where you can use an equal sign between a keyword argument and the value (like `--add-tags=foo`), but since `query` is a positional argument, this won't work. In that case, you can just put a space after the double quote (like `" -deepbooru"`).

Maybe there is an option for argparse to tweak that behavior, I'll take a look sometime this weekend. Then I'll also update the crontab command and push a new tag.

**Comment by reluce** [comment]
I updated the argparse logic, so if the query starts with a `-`, no errors get thrown in any of the scripts now (https://github.com/reluce/szurubooru-toolkit/commit/16ddbff3da0d2e202394f3dc36488460d211ee23).
