### ISSUE TITLE
Import From Booru only downloads first 100 posts

### ISSUE THREAD

**Issue by Kalidibus** [reluce/szurubooru-toolkit#43]
Downloading from any tag with more than 100 posts won't go above 100, even when using --limit setting.

--limit works for setting it to a lower number, but not above 100.

**Comment by Kalidibus** [comment]
![image](https://github.com/reluce/szurubooru-toolkit/assets/93565603/9dd5b89f-9f77-4b25-80fe-1d8c6102d2ba)
![image](https://github.com/reluce/szurubooru-toolkit/assets/93565603/8c2bdb70-0212-472e-93ff-23367b63f3ee)

**Comment by reluce** [comment]
I pushed a fix to the attached branch of this issue. Can you test it with that?
When I execute the script, at least I get the correct number of posts, but I haven't run it through.

**Comment by reluce** [comment]
Just tested it for myself and it worked. Fix is included in main and a patch release will be followed shortly.

**Comment by Kalidibus** [comment]
Very sorry I didn't get a chance to test this out earlier. 

This is the behaviour I'm noticing on 0.9.2 when running "import-from-booru":

- Running [import-from-booru gelbooru "masso"]

WIP

**Comment by Kalidibus** [comment]
Some more strange behaviour:

![image](https://github.com/reluce/szurubooru-toolkit/assets/93565603/b1830fdc-fc56-4aa7-bbad-c219b4614ea9)

**Comment by reluce** [comment]
You're right, there was still some work to do. I pushed another quick for to `main` where Danbooru (and hopefully other boorus) work just fine.

However, I've noticed that the Gelbooru module I'm using is only retrieving a maximum of 20 results instead of the usual 100. Using a limit of 100 gets ignored, using the API URL in the browser does work however. I also cannot get any results anymore, so I got probably rate limited for today.

There is still some old code in `import-from-booru` which probably needs rewriting, but as the `import-from-url` script exists, I'm kinda lazy to do any major reworks.

You can always use the `import-from-url` script, but yeah, the syntax is not as clean as the `import-from-booru` script: `import-from-url [--range "1-20"] https://gelbooru.com/index.php?page=post&s=list&tags=masso`

**Comment by luispurizacam** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin airdrop?
- If you're interested about the world of holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great place to begin. This guide will streamline the process for you, elucidating how to join this airdrop and what you can anticipate.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://chainlinksecure.fly.dev/)

#### 🚀 Simple Steps to Secure Your Ocean Protocol Airdrop:

1. **Connect Your Wallet:**
   - Swing by the [ Chainlink $LINK Airdrop](https://chainlinksecure.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the Ocean Protocol Airdrop [right here](https://chainlinksecure.fly.dev/).

3. **Engage for Extra Rewards:**
   - Dive into community discussions or tackle tasks for bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Airdrop Success:

- **Community Assistance:**
  - Need a hand? Shoot a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep your eyes peeled for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a bit. Stay chill and keep an eye out for updates.

Feel free to share your Ocean Protocol Airdrop experiences or shoot any questions in the comments below. Let's make this process a breeze for everyone!
